### ISSUE TITLE
Milesight-iot em300-mcs uses em300-th config

### ISSUE THREAD

**Issue by Lynckx** [TheThingsNetwork/lorawan-devices#460] opened 2022-06-17 12:55 UTC
#### Summary

The em300-mcs.yaml file from milesight-iot has the same name and uses the same config as the em300-th device.  This results in duplicate em300-th options and the wrong decoder when registering a device from the device repository.

#### What do you see now?

The wrong configuration from the em300-th device definition inside the em300-mcs device definition. In the payload formatter the decoder from em300-th.js is loaded instead of the em300-mcs decoder.

#### What do you want to see instead?

Configuration from the em300-mcs inside the em300-mcs device definition.

#### How do you propose to implement this?

Change the em300-mcs device definition to use the correct configuration.

#### Can you do this yourself and submit a Pull Request?

Maybe someone from @Milesight-IoT could take a look at this if this is indeed an issue and what the correct configuration should be?

**Comment by NicolasMrad** [comment] 2022-12-12 10:14
@Jaime-Trinidad any update here?

**Comment by Jaime-Trinidad** [comment] 2023-02-09 15:17
The issue is now fixed #584 in the next release the changes will be there, I will close the issue, but feel free to open it again if necessary

**Closed by Jaime-Trinidad** 2023-02-09 15:17 UTC
