### ISSUE TITLE
RCM-H200 device profile causes error in trace log on TTN

### ISSUE THREAD

**Issue by maebli** [TheThingsNetwork/lorawan-devices#544] opened 2022-10-21 13:50 UTC
#### Summary
The newly created profile of RCM-h200 was used to commission a new device. The following error was seen.

![grafik](https://user-images.githubusercontent.com/1138612/197211219-c098b962-3806-4d2d-b279-c6666bac045f.png)

#### What do you see now?
Error in trace log.

#### What do you want to see instead?
No error in trace log.

#### How do you propose to implement this?
Find out what is wrong with the decoder, which is undefined. 

#### Can you do this yourself and submit a Pull Request?
No

**Comment by Jaime-Trinidad** [comment] 2022-10-31 10:10
Hi @maebli who is the vendor?

**Comment by maebli** [comment] 2022-10-31 10:12
GwfMesssysteme Ag

**Comment by NicolasMrad** [comment] 2022-12-12 10:12
@Jaime-Trinidad any update here?

**Comment by Jaime-Trinidad** [comment] 2023-01-17 17:36
Hi @maebli , I make some tests the problem is in the decoder file with the function `decodeUplink`, this will be fixed in the next release

The actual problem with `decoder.js`
<img width="1142" alt="Screenshot 2023-01-17 at 18 32 04" src="https://user-images.githubusercontent.com/81958808/212971252-8bd1e87f-f679-4fac-9da6-488ec3e62fc7.png">

Problem fixed, no more error in the console
<img width="1138" alt="Screenshot 2023-01-17 at 18 32 22" src="https://user-images.githubusercontent.com/81958808/212971400-67fca5fb-7f96-4e68-b12d-9c1961db7425.png">

**Comment by Jaime-Trinidad** [comment] 2023-01-17 21:38
Problem should be solved with PR #581, I will close this issue, feel free to open it if necessary

**Closed by Jaime-Trinidad** 2023-01-17 21:38 UTC
